### ISSUE TITLE
同社区节点联系紧密，不同社区节点联系稀疏效果

### ISSUE THREAD

**Issue by yzuaiyou** [QinY-Stat/CommunityDetection#2]
你好 
请问下
com_dict = {node:com for node, com in zip(V, a)}
a 值得是什么？直接调试会报错

**Comment by qinyuenlp** [comment]
您好，a是得到的节点所在社区的列表（即sc_com或GN_com）。这是由于本人的疏忽造成的，该错误目前已经修改，感谢您的指正！
