### ISSUE TITLE
AttributeError: module 'community' has no attribute 'modularity'

### ISSUE THREAD

**Issue by Fanderbio** [QinY-Stat/CommunityDetection#4]

**Comment by Fanderbio** [comment]
使用GN算法时出现错误：
AttributeError: module 'community' has no attribute 'modularity'

**Comment by QinY-Stat** [comment]
pip install python-louvain

**Comment by qinyuenlp** [comment]
pip install python-louvain
然后再运行就ok，这是借用了python-louvain项目中写的modularity函数，但在python语句中需要用import community来调用

**Comment by chenzc0101** [comment]
Still can't work after installing puthon-louvain

**Comment by chenzc0101** [comment]
For my case, I need to change community to community_louvain. Then the code works

**Comment by qinyuenlp** [comment]
> For my case, I need to change community to community_louvain. Then the code works

Try running `pip uninstall community` after installing `python-louvain`.
