### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by 0215Arthur** [QinY-Stat/CommunityDetection#5]
求教

一些gml 无法读取，read_gml会报错:
networkx.exception.NetworkXError: node #0 has no 'label' attribute

power,netscience都会报错，这个怎么修改呢？

**Comment by QinY-Stat** [comment]
1.这是由于gml数据本身在存储节点的时候没有给节点添加label属性造成的。通常来说，每个节点都会有一个id，在大部分数据中还会给节点一个label来标识该节点在网络中的意义，一般是一个实体名词。
2.在networkx.read_gml()函数中，有一个label参数，其默认值是"label"，通过调整这个参数，可以根据不同的节点属性来读取网络数据。我检查了一下，power数据集中的节点仅有id属性，这样可以用networkx.read_gml(power.gml, label="id")来读取；而netscience数据集应该是可以直接用networkx.read_gml(netscience.gml)读取的。
3.为了避免这个error，可以在读取前先查看数据集，再根据需要调整参数即可。

**Comment by qinyuenlp** [comment]
> 
> 
> 求教
> 
> 一些gml 无法读取，read_gml会报错:
> networkx.exception.NetworkXError: node #0 has no 'label' attribute
> 
> power,netscience都会报错，这个怎么修改呢？

1.这是由于gml数据本身在存储节点的时候没有给节点添加label属性造成的。通常来说，每个节点都会有一个id，在大部分数据中还会给节点一个label来标识该节点在网络中的意义，一般是一个实体名词。
2.在networkx.read_gml()函数中，有一个label参数，其默认值是"label"，通过调整这个参数，可以根据不同的节点属性来读取网络数据。我检查了一下，power数据集中的节点仅有id属性，这样可以用networkx.read_gml(power.gml, label="id")来读取；而netscience数据集应该是可以直接用networkx.read_gml(netscience.gml)读取的。
3.为了避免这个error，可以在读取前先查看数据集，再根据需要调整参数即可。

**Comment by 0215Arthur** [comment]
> > 求教
> > 一些gml 无法读取，read_gml会报错:
> > networkx.exception.NetworkXError: node #0 has no 'label' attribute
> > power,netscience都会报错，这个怎么修改呢？
> 
> 1.这是由于gml数据本身在存储节点的时候没有给节点添加label属性造成的。通常来说，每个节点都会有一个id，在大部分数据中还会给节点一个label来标识该节点在网络中的意义，一般是一个实体名词。
> 2.在networkx.read_gml()函数中，有一个label参数，其默认值是"label"，通过调整这个参数，可以根据不同的节点属性来读取网络数据。我检查了一下，power数据集中的节点仅有id属性，这样可以用networkx.read_gml(power.gml, label="id")来读取；而netscience数据集应该是可以直接用networkx.read_gml(netscience.gml)读取的。
> 3.为了避免这个error，可以在读取前先查看数据集，再根据需要调整参数即可。

十分感谢！
